version: '3'
services:

  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    
    ports:
      - "8086:8086"
      - "25826:25826/udp"
    
    volumes:
      - ./influxdb/db:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
         
  telegraf:
    image: telegraf:latest
    container_name: "telegraf"
    
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
    depends_on:
      - influxdb
      
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    
    volumes:
      - ./grafana/db:/var/lib/grafana

    ports:
      - "3000:3000"
    
    depends_on:
      - influxdb
      - telegraf



